#!/usr/bin/env bash
# audience-reset.sh — One-stop demo environment setup and reset for OpenClaw
#
# Deploys Claw instances if they don't exist, then resets all instances with
# new unique URLs, deploys FantaCo backends, injects MCP endpoints and
# enterprise skills. Run update-broker.sh afterwards to publish to the broker.
#
# This script consolidates:
#   - 1-deploy-claw.sh (Claw CR + secrets, if not already deployed)
#   - audience-reset (URL rotation, state wipe)
#   - 4-deploy-fantaco-backends.sh (Helm deploy)
#   - 5-inject-mcp-endpoints.sh (MCP CR patch + NetworkPolicy)
#   - 6-inject-enterprise-skills.sh (skill injection)
#
# Usage:
#   ./audience-reset.sh              # reset all agentic-user namespaces on cluster
#   ./audience-reset.sh 1 5          # reset user1 through user5
#   ./audience-reset.sh 3            # just user3
#
# Environment variables:
#   NAMESPACE_PREFIX — namespace prefix (default: agentic-user)

set -euo pipefail

NAMESPACE_PREFIX="${NAMESPACE_PREFIX:-agentic-user}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLUSTER_GUID=$(oc cluster-info 2>/dev/null | head -1 | sed 's|.*api\.ocp\.\([^.]*\)\..*|\1|')
if [[ -z "$CLUSTER_GUID" ]]; then
  echo "Error: could not extract cluster GUID from 'oc cluster-info'" >&2
  exit 1
fi
ENV_FILE="${SCRIPT_DIR}/../.env"
HELM_DIR="${SCRIPT_DIR}/../helm"
SKILLS_DIR="${SCRIPT_DIR}/../claw_skills"
SKILLS_DEST="/home/node/.openclaw/workspace/skills"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# ── Source .env (needed for model re-patching and password display) ──
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi
# Source Langfuse keys from cluster state (generated by deploy-traces-langfuse.sh)
LANGFUSE_STATE="${SCRIPT_DIR}/.state/${CLUSTER_GUID}/langfuse.env"
if [[ -f "$LANGFUSE_STATE" ]]; then
  # shellcheck disable=SC1090
  source "$LANGFUSE_STATE"
  LANGFUSE_PUBLIC_KEY="${INIT_PUBLIC_KEY:-}"
  LANGFUSE_SECRET_KEY="${INIT_SECRET_KEY:-}"
fi
LLM_PROVIDER="${LLM_PROVIDER:-}"
STUDENT_OPENCLAW_PASSWORD="${STUDENT_OPENCLAW_PASSWORD:-}"

# ── Helper: wait for gateway to be exec-ready ──────────────────────
# After rollout restart, the pod may not be ready for exec even though
# oc rollout status returned. This waits up to 60s for node to respond.
wait_for_exec_ready() {
  local ns=$1
  local max_wait=${2:-30}
  for _attempt in $(seq 1 "$max_wait"); do
    if oc exec deployment/instance -n "$ns" -c gateway -- node -e "console.log('ready')" &>/dev/null; then
      return 0
    fi
    sleep 2
  done
  echo -e "  ${YELLOW}⚠${RESET} $ns: gateway not exec-ready after $((max_wait * 2))s"
  return 1
}

# ── Route-LB broker config (resolved after arg parsing via resolve-site.sh) ─

# ── Helm template lists (from 4-deploy-fantaco-backends.sh) ────────
CUSTOMER_APP_TEMPLATES=(
  templates/postgres-customer-deployment.yaml
  templates/postgres-customer-service.yaml
  templates/customer-configmap.yaml
  templates/customer-secret.yaml
  templates/customer-deployment.yaml
  templates/customer-service.yaml
  templates/customer-route.yaml
)

CUSTOMER_MCP_TEMPLATES=(
  templates/customer-deployment.yaml
  templates/customer-service.yaml
  templates/customer-route.yaml
)

SALESORDER_APP_TEMPLATES=(
  templates/postgres-salesorder-deployment.yaml
  templates/postgres-salesorder-service.yaml
  templates/salesorder-configmap.yaml
  templates/salesorder-secret.yaml
  templates/salesorder-deployment.yaml
  templates/salesorder-service.yaml
  templates/salesorder-route.yaml
)

SALESORDER_MCP_TEMPLATES=(
  templates/salesorder-deployment.yaml
  templates/salesorder-service.yaml
  templates/salesorder-route.yaml
)

PRODUCT_APP_TEMPLATES=(
  templates/postgres-product-deployment.yaml
  templates/postgres-product-service.yaml
  templates/product-configmap.yaml
  templates/product-secret.yaml
  templates/product-deployment.yaml
  templates/product-service.yaml
  templates/product-route.yaml
)

PRODUCT_MCP_TEMPLATES=(
  templates/product-deployment.yaml
  templates/product-service.yaml
  templates/product-route.yaml
)

# ── Skills to inject ──────────────────────────────────────────────
SKILLS=(
  quote-builder
)

# ── Helper: render and apply Helm templates ───────────────────────
apply_templates() {
  local chart_name=$1
  local chart_dir=$2
  local ns=$3
  shift 3
  local templates=("$@")

  local show_args=()
  for t in "${templates[@]}"; do
    show_args+=(-s "$t")
  done

  helm template "$chart_name" "$chart_dir" -n "$ns" "${show_args[@]}" \
    | oc apply -n "$ns" -f - 2>&1 | sed 's/^/    /'
}

# ── Helper: wait for pods matching a grep pattern ─────────────────
wait_for_pods() {
  local ns=$1
  local pattern=$2
  local expected=$3
  local label=$4

  SECONDS=0
  local ready=0
  while [[ $SECONDS -lt 120 ]]; do
    ready=$(oc get pods -n "$ns" --no-headers 2>/dev/null \
      | grep -E "$pattern" \
      | grep -c "Running" || true)
    if [[ $ready -ge $expected ]]; then
      break
    fi
    sleep 5
  done

  if [[ $ready -ge $expected ]]; then
    echo -e "  ${GREEN}✓${RESET} $label: $ready/$expected pods running"
  else
    echo -e "  ${YELLOW}⚠${RESET} $label: only $ready/$expected pods running after 120s"
  fi
  return 0
}

# ── Argument parsing ────────────────────────────────────────────────
# Extract --site flag before positional args
POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --site) SITE_NAME="$2"; shift 2 ;;
    *) POSITIONAL_ARGS+=("$1"); shift ;;
  esac
done
set -- "${POSITIONAL_ARGS[@]+"${POSITIONAL_ARGS[@]}"}"

# Load site config (BROKER_DOMAIN, BROKER_S3_BUCKET, etc.)
source "${SCRIPT_DIR}/sites/resolve-site.sh"

NAMESPACES=()
if [[ $# -eq 0 ]]; then
  # No args — discover all agentic-user namespaces on cluster
  if ! oc whoami &>/dev/null; then
    echo "Error: Not logged in to OpenShift. Run 'oc login' first."
    exit 1
  fi
  while IFS= read -r ns; do
    NAMESPACES+=("$ns")
  done < <(oc get namespaces --no-headers 2>/dev/null | awk '{print $1}' | grep "^${NAMESPACE_PREFIX}" | sort -V)
  if [[ ${#NAMESPACES[@]} -eq 0 ]]; then
    echo "Error: No ${NAMESPACE_PREFIX}* namespaces found on cluster."
    exit 1
  fi
elif [[ $# -le 2 ]]; then
  START=$1
  END=${2:-$START}
  if [[ $START -gt $END ]]; then
    echo "Error: start ($START) must be <= end ($END)"
    exit 1
  fi
  for i in $(seq "$START" "$END"); do
    NAMESPACES+=("${NAMESPACE_PREFIX}${i}")
  done
else
  echo "Usage: $0                # reset all agentic-user namespaces"
  echo "       $0 <start> [end]  # reset agentic-user<start> through agentic-user<end>"
  exit 1
fi

# ── Verify oc login ─────────────────────────────────────────────────
if ! oc whoami &>/dev/null; then
  echo "Error: Not logged in to OpenShift. Run 'oc login' first."
  exit 1
fi

echo ""
SCRIPT_START_EPOCH=$(date +%s)

echo -e "${BOLD}============================================${RESET}"
echo -e "${BOLD}  Audience Reset${RESET}"
echo -e "${BOLD}============================================${RESET}"
echo ""
echo -e "Logged in as: ${CYAN}$(oc whoami)${RESET}"
echo ""
echo -e "Namespaces:"
for NS in "${NAMESPACES[@]}"; do
  echo -e "  - ${CYAN}${NS}${RESET}"
done
echo ""

# ── Derive apps domain (from ingress config, works even without Routes) ──
APPS_DOMAIN=$(oc get ingresses.config/cluster -o jsonpath='{.spec.domain}' 2>/dev/null || true)
if [[ -z "$APPS_DOMAIN" ]]; then
  echo "Error: Could not derive apps domain from ingress config."
  exit 1
fi
echo -e "Apps domain: ${CYAN}${APPS_DOMAIN}${RESET}"

# ── Early Langfuse detection (needed for Phase 0 Claw CR credentials) ──
LANGFUSE_ROUTE=$(oc get route langfuse -n langfuse -o jsonpath='{.spec.host}' 2>/dev/null || true)
if [[ -n "$LANGFUSE_ROUTE" ]]; then
  LANGFUSE_URL="https://${LANGFUSE_ROUTE}"
fi

# ══════════════════════════════════════════════════════════════════════
# Phase 0: Ensure Claw instances exist (create if missing)
# ══════════════════════════════════════════════════════════════════════

# Check if any namespace is missing a Claw CR
MISSING_NS=()
EXISTING_NS=()
for NS in "${NAMESPACES[@]}"; do
  if oc get claw instance -n "$NS" &>/dev/null; then
    EXISTING_NS+=("$NS")
  else
    MISSING_NS+=("$NS")
  fi
done

if [[ ${#MISSING_NS[@]} -gt 0 ]]; then
  echo ""
  echo -e "${BOLD}--- Phase 0: Deploying Claw instances (${#MISSING_NS[@]} namespaces) ---${RESET}"

  # Build credentials YAML based on provider
  build_claw_credentials_yaml() {
    case "${LLM_PROVIDER:-litellm}" in
      litellm)
        local domain
        domain=$(echo "${LLM_API_BASE_URL:-}" | sed -E 's|^https?://||' | sed 's|/.*||')
        cat <<CRED
    - name: litellm
      type: bearer
      secretRef:
        - name: litellm-api-key
          key: api-key
      domain: ${domain}
      provider: openai
CRED
        ;;
      anthropic)
        cat <<CRED
    - name: anthropic
      type: apiKey
      secretRef:
        - name: anthropic-api-key
          key: api-key
      provider: anthropic
CRED
        ;;
      openai)
        cat <<CRED
    - name: openai
      type: apiKey
      secretRef:
        - name: openai-api-key
          key: api-key
      provider: openai
CRED
        ;;
      gcp)
        cat <<CRED
    - name: gcp-vertex
      type: gcp
      secretRef:
        - name: gcp-service-account
          key: sa-key.json
      domain: .googleapis.com
      provider: google
      gcp:
        project: ${GOOGLE_CLOUD_PROJECT:-}
        location: ${GOOGLE_CLOUD_LOCATION:-us-central1}
CRED
        ;;
      openrouter)
        cat <<CRED
    - name: openrouter
      type: bearer
      secretRef:
        - name: openrouter-api-key
          key: api-key
      domain: openrouter.ai
      provider: openai
CRED
        ;;
    esac

    # Append Langfuse credential (proxy injects Basic Auth — keys never reach gateway pod)
    if [[ -n "${LANGFUSE_ROUTE:-}" && -n "${LANGFUSE_PUBLIC_KEY:-}" && -n "${LANGFUSE_SECRET_KEY:-}" ]]; then
      cat <<CRED
    - name: langfuse
      type: apiKey
      domain: ${LANGFUSE_ROUTE}
      secretRef:
        - name: langfuse-auth
          key: basic-auth
      apiKey:
        header: authorization
        valuePrefix: "Basic "
CRED
    fi
  }

  CLAW_CREDENTIALS_YAML=$(build_claw_credentials_yaml)

  # Determine secret name and value
  case "${LLM_PROVIDER:-litellm}" in
    litellm)    CLAW_SECRET_NAME="litellm-api-key";    CLAW_SECRET_KEY="api-key"; CLAW_SECRET_VALUE="${LLM_API_KEY:-}" ;;
    anthropic)  CLAW_SECRET_NAME="anthropic-api-key";   CLAW_SECRET_KEY="api-key"; CLAW_SECRET_VALUE="${ANTHROPIC_API_KEY:-}" ;;
    openai)     CLAW_SECRET_NAME="openai-api-key";      CLAW_SECRET_KEY="api-key"; CLAW_SECRET_VALUE="${OPENAI_API_KEY:-}" ;;
    gcp)        CLAW_SECRET_NAME="gcp-service-account";  CLAW_SECRET_KEY="" ;;
    openrouter) CLAW_SECRET_NAME="openrouter-api-key";   CLAW_SECRET_KEY="api-key"; CLAW_SECRET_VALUE="${OPENROUTER_API_KEY:-}" ;;
  esac

  for NS in "${MISSING_NS[@]}"; do
    echo -e "  ${CYAN}${NS}${RESET}: Creating secrets + Claw CR..."

    # Create API key secret
    if [[ "${LLM_PROVIDER:-litellm}" == "gcp" ]]; then
      oc create secret generic "$CLAW_SECRET_NAME" \
        --from-file=sa-key.json="${GOOGLE_APPLICATION_CREDENTIALS:-}" \
        -n "$NS" --dry-run=client -o yaml | oc apply -f -
    else
      oc create secret generic "$CLAW_SECRET_NAME" \
        --from-literal=api-key="$CLAW_SECRET_VALUE" \
        -n "$NS" --dry-run=client -o yaml | oc apply -f -
    fi

    # Create Langfuse auth secret (Basic Auth credential for proxy injection)
    if [[ -n "${LANGFUSE_PUBLIC_KEY:-}" && -n "${LANGFUSE_SECRET_KEY:-}" ]]; then
      LANGFUSE_BASIC_AUTH=$(echo -n "${LANGFUSE_PUBLIC_KEY}:${LANGFUSE_SECRET_KEY}" | base64)
      oc create secret generic langfuse-auth \
        --from-literal=basic-auth="$LANGFUSE_BASIC_AUTH" \
        -n "$NS" --dry-run=client -o yaml | oc apply -f -
    fi

    # Apply Claw CR (token auth — each instance gets a unique token from operator)
    oc apply -n "$NS" -f - <<EOF
apiVersion: claw.sandbox.redhat.com/v1alpha1
kind: Claw
metadata:
  name: instance
spec:
  auth:
    mode: token
    disableDevicePairing: true
  credentials:
${CLAW_CREDENTIALS_YAML}
EOF
  done

  # Wait for all new pods to come up
  echo ""
  echo -e "  Waiting for pods (up to 120s)..."
  for NS in "${MISSING_NS[@]}"; do
    SECONDS=0
    while [[ $SECONDS -lt 120 ]]; do
      READY=$(oc get pods -n "$NS" -l claw.sandbox.redhat.com/instance=instance \
        --no-headers 2>/dev/null | grep -c "Running" || true)
      if [[ $READY -ge 3 ]]; then break; fi
      sleep 5
    done
    if [[ $READY -ge 3 ]]; then
      echo -e "  ${GREEN}✓${RESET} $NS: all $READY pods running"
    else
      echo -e "  ${RED}⚠${RESET} $NS: only ${READY}/3 pods running after 120s"
    fi
  done
  echo ""
fi

if [[ ${#EXISTING_NS[@]} -gt 0 ]]; then
  echo -e "Claw instances already deployed: ${GREEN}${#EXISTING_NS[@]}${RESET} namespaces"
  # Ensure existing Claw CRs use token auth (idempotent — no-op if already set)
  echo "  Patching existing CRs to token auth mode..."
  for NS in "${EXISTING_NS[@]}"; do
    oc patch claw instance -n "$NS" --type=merge \
      -p '{"spec":{"auth":{"mode":"token","disableDevicePairing":true}}}' 2>/dev/null || true
  done
fi
if [[ ${#MISSING_NS[@]} -gt 0 ]]; then
  echo -e "Claw instances created:          ${GREEN}${#MISSING_NS[@]}${RESET} namespaces"
fi

# Generate a shared audience code (visible in all URLs for this run)
AUDIENCE_CODE="${AUDIENCE_CODE:-$(head -c 4 /dev/urandom | xxd -p | head -c 5)}"
echo -e "Audience:   ${CYAN}${AUDIENCE_CODE}${RESET}"

# Save AUDIENCE_CODE so update-broker.sh can read it without --audience-code flag
mkdir -p "${SCRIPT_DIR}/.state/${CLUSTER_GUID}"
echo "AUDIENCE_CODE=${AUDIENCE_CODE}" > "${SCRIPT_DIR}/.state/${CLUSTER_GUID}/broker.env"
chmod 600 "${SCRIPT_DIR}/.state/${CLUSTER_GUID}/broker.env"
echo ""

# ══════════════════════════════════════════════════════════════════════
# Detect OTEL / Trace Backends (needed for Phase 1 env vars + Phase 3 plugins)
# ══════════════════════════════════════════════════════════════════════
# The diagnostics-otel plugin requires three things to export traces:
#   1. The plugin npm package must be installed (@openclaw/diagnostics-otel)
#   2. The diagnostics.otel config block must be set (enabled, protocol, traces, sampleRate)
#   3. OTEL env vars must be set as real container env vars (not just in openclaw.json env section)
# The gateway pod egresses through instance-proxy; the proxy allowlist does NOT include
# MLflow or Langfuse. We use internal cluster service URLs (*.svc.cluster.local) which
# bypass the proxy (matched by NO_PROXY=.svc.cluster.local) and NetworkPolicies for egress.
#
# Priority: Langfuse > MLflow (if both are deployed, Langfuse wins for OTEL_BACKEND label)
OTEL_PATCHED=false
OTEL_BACKEND=""
OTEL_ENDPOINT=""
OTEL_HEADERS=""
OTEL_INTERNAL_URL=""

# Detect MLflow
MLFLOW_URL=""
MLFLOW_INTERNAL_URL=""
EXPERIMENT_ID=""
MLFLOW_ROUTE=$(oc get route mlflow -n mlflow -o jsonpath='{.spec.host}' 2>/dev/null || true)
if [[ -n "$MLFLOW_ROUTE" ]]; then
  MLFLOW_URL="https://${MLFLOW_ROUTE}"
  MLFLOW_INTERNAL_URL="http://mlflow-mlflow.mlflow.svc.cluster.local:5000"
  EXPERIMENT_ID=$(curl -sk "${MLFLOW_URL}/api/2.0/mlflow/experiments/get-by-name?experiment_name=openclaw-traces" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['experiment']['experiment_id'])" 2>/dev/null || echo "1")
  OTEL_BACKEND="MLflow"
  OTEL_ENDPOINT="${MLFLOW_INTERNAL_URL}/v1/traces"
  OTEL_HEADERS="x-mlflow-experiment-id=${EXPERIMENT_ID}"
  OTEL_INTERNAL_URL="${MLFLOW_INTERNAL_URL}"
fi

# Save MLflow OTEL values (diagnostics-otel always targets MLflow when available)
MLFLOW_OTEL_ENDPOINT="${OTEL_ENDPOINT}"
MLFLOW_OTEL_HEADERS="${OTEL_HEADERS}"

# Detect Langfuse (langfuse-tracer handles traces via REST API, NOT diagnostics-otel)
# LANGFUSE_ROUTE and LANGFUSE_URL already set in early detection above
LANGFUSE_INTERNAL_URL=""
if [[ -n "$LANGFUSE_ROUTE" && -n "${LANGFUSE_PUBLIC_KEY:-}" && -n "${LANGFUSE_SECRET_KEY:-}" ]]; then
  LANGFUSE_INTERNAL_URL="http://langfuse-web.langfuse.svc.cluster.local:3000"
  OTEL_BACKEND="Langfuse"
  OTEL_INTERNAL_URL="${LANGFUSE_URL}"
  # OTEL_ENDPOINT/HEADERS stay pointed at MLflow (diagnostics-otel → MLflow)
  # langfuse-tracer uses external LANGFUSE_URL via the claw-operator proxy
  # (keys are injected by proxy, never exposed to gateway pod)
elif [[ -n "$LANGFUSE_ROUTE" ]]; then
  echo -e "  ${YELLOW}Langfuse deployed but LANGFUSE_PUBLIC_KEY/SECRET_KEY not in .env — skipping${RESET}"
fi

if [[ -n "$OTEL_BACKEND" ]]; then
  echo -e "${BOLD}--- Detected trace backend: ${OTEL_BACKEND} → ${OTEL_INTERNAL_URL} ---${RESET}"
  if [[ "$OTEL_BACKEND" == "Langfuse" ]]; then
    echo "  Backend:       Langfuse (priority over MLflow)"
    echo "  External URL:  ${LANGFUSE_URL}"
    echo "  Internal URL:  ${LANGFUSE_INTERNAL_URL}"
    [[ -n "$MLFLOW_ROUTE" ]] && echo "  MLflow:        also deployed (${MLFLOW_URL}) — diagnostics-otel still targets it"
  else
    echo "  Backend:       MLflow"
    echo "  Experiment ID: ${EXPERIMENT_ID}"
    echo "  External URL:  ${MLFLOW_URL}"
    echo "  Internal URL:  ${MLFLOW_INTERNAL_URL}"
  fi
  echo ""
fi

# ── Reset Prometheus data (wipe old audience metrics) ──────────────
# Prometheus User Workload Monitoring uses emptyDir — deleting pods wipes all data.
if oc get sts prometheus-user-workload -n openshift-user-workload-monitoring &>/dev/null; then
  echo -e "${BOLD}--- Resetting Prometheus data ---${RESET}"
  echo "  Deleting Prometheus pods (emptyDir — data wiped on recreate)..."
  oc delete pods -n openshift-user-workload-monitoring -l app.kubernetes.io/name=prometheus --wait=false 2>/dev/null || true
  echo "  Waiting for Prometheus pods to come back..."
  oc rollout status sts/prometheus-user-workload -n openshift-user-workload-monitoring --timeout=120s 2>/dev/null || true
  echo ""
fi

# ── Reset Grafana dashboard ────────────────────────────────────────
if oc get grafanadashboard openclaw-admin-overview -n grafana &>/dev/null; then
  echo -e "${BOLD}--- Resetting Grafana dashboard ---${RESET}"
  echo "  Deleting and re-applying openclaw-admin-overview..."
  DASHBOARD_JSON=$(oc get grafanadashboard openclaw-admin-overview -n grafana -o json 2>/dev/null)
  oc delete grafanadashboard openclaw-admin-overview -n grafana --wait=true 2>/dev/null || true
  # Re-create from the saved spec (strip runtime metadata)
  echo "$DASHBOARD_JSON" | python3 -c "
import sys, json
d = json.load(sys.stdin)
# Keep only spec + essential metadata
out = {
    'apiVersion': d['apiVersion'],
    'kind': d['kind'],
    'metadata': {
        'name': d['metadata']['name'],
        'namespace': d['metadata']['namespace']
    },
    'spec': d['spec']
}
json.dump(out, sys.stdout)
" | oc apply -f - 2>&1 | sed 's/^/    /'
  echo ""
fi

# ══════════════════════════════════════════════════════════════════════
# Phase 1: Per-namespace reset (wipe, deploy backends, new route, restart)
#          Runs up to MAX_PARALLEL namespaces concurrently.
# ══════════════════════════════════════════════════════════════════════
MAX_PARALLEL=${MAX_PARALLEL:-5}
SUCCESS_COUNT=0
FAIL_COUNT=0
declare -a AUDIENCE_URLS=()
declare -a AUDIENCE_HOSTS=()
declare -a AUDIENCE_LABELS=()

PHASE1_TMPDIR=$(mktemp -d)

echo -e "${BOLD}--- Phase 1: Resetting ${#NAMESPACES[@]} namespaces (${MAX_PARALLEL} parallel) ---${RESET}"
echo ""

declare -a PIDS=()

for idx in "${!NAMESPACES[@]}"; do
  NS="${NAMESPACES[$idx]}"
  USER_NUM="${NS#${NAMESPACE_PREFIX}}"

  # Generate unique 6-char random code for this user
  USER_CODE=$(head -c 6 /dev/urandom | xxd -p | head -c 6)
  AUDIENCE_HOST="claw-${AUDIENCE_CODE}-${USER_CODE}.${APPS_DOMAIN}"
  AUDIENCE_URL="https://${AUDIENCE_HOST}"

  # Write parent-generated values to result file
  cat > "${PHASE1_TMPDIR}/${NS}.result" <<RESEOF
URL=${AUDIENCE_URL}
HOST=${AUDIENCE_HOST}
LABEL=${USER_NUM}
RESEOF

  echo -e "  ${CYAN}${NS}${RESET}: ${GREEN}${AUDIENCE_URL}${RESET}"

  # ── Launch per-namespace worker in background subshell ──
  (
    LOG="${PHASE1_TMPDIR}/${NS}.log"
    NS_START_EPOCH=$(date +%s)

    {
      echo "=== Resetting namespace: $NS ===  ($(date +%H:%M:%S))"
      echo "  New URL: ${AUDIENCE_URL}"

      # 1a. Delete existing audience Route (old URL dies immediately)
      if oc get route audience -n "$NS" &>/dev/null; then
        echo "  Deleting previous audience Route..."
        oc delete route audience -n "$NS" --wait=false 2>/dev/null || true
      fi

      # 1b. Verify gateway pod is running
      POD=$(oc get pods -n "$NS" -l claw.sandbox.redhat.com/instance=instance -l app=claw \
        --no-headers -o custom-columns=NAME:.metadata.name 2>/dev/null | head -1)
      if [[ -z "$POD" ]]; then
        echo "  WARN: No gateway pod found — skipping."
        echo "STATUS=fail" >> "${PHASE1_TMPDIR}/${NS}.result"
        exit 0
      fi

      # 1c. Wipe user state
      echo "  Wiping user state..."
      oc exec deployment/instance -n "$NS" -c gateway -- node -e "
        const { execSync } = require('child_process');
        const fs = require('fs');
        const path = require('path');
        const HOME = '/home/node/.openclaw';

        const dirsToRemove = [
          HOME + '/agents/default/sessions',
          HOME + '/agents/main/agent/codex-home/tmp',
          HOME + '/cron/runs',
          HOME + '/.cache',
          HOME + '/.local',
        ];

        const filesToRemove = [
          HOME + '/agents/main/agent/codex-home/installation_id',
          HOME + '/agents/main/agent/codex-home/.personality_migration',
          HOME + '/cron/jobs.json',
          HOME + '/cron/jobs.json.bak',
          HOME + '/cron/jobs-state.json',
          HOME + '/memory/default.sqlite',
          HOME + '/memory/default.sqlite-wal',
          HOME + '/memory/default.sqlite-shm',
          HOME + '/tasks/runs.sqlite',
          HOME + '/tasks/runs.sqlite-wal',
          HOME + '/tasks/runs.sqlite-shm',
          HOME + '/workspace/.openclaw/workspace-state.json',
          HOME + '/workspace/USER.md',
          HOME + '/workspace/HEARTBEAT.md',
          HOME + '/workspace/IDENTITY.md',
          HOME + '/workspace/SOUL.md',
          HOME + '/identity/device.json',
          HOME + '/openclaw.json',
          HOME + '/openclaw.json.last-good',
          HOME + '/update-check.json',
          HOME + '/logs/config-health.json',
        ];

        let removed = 0;

        for (const d of dirsToRemove) {
          try { execSync('rm -rf ' + JSON.stringify(d), { stdio: 'pipe' }); removed++; } catch (e) {}
        }
        for (const f of filesToRemove) {
          try { fs.unlinkSync(f); removed++; } catch (e) {}
        }

        const codexHome = HOME + '/agents/main/agent/codex-home';
        try {
          const entries = fs.readdirSync(codexHome);
          for (const e of entries) {
            if (/^(state_|logs_).*\\.sqlite/.test(e)) {
              fs.unlinkSync(path.join(codexHome, e));
              removed++;
            }
          }
        } catch (e) {}

        const skillsDir = HOME + '/workspace/skills';
        try {
          const entries = fs.readdirSync(skillsDir);
          for (const e of entries) {
            if (e !== 'platform') {
              execSync('rm -rf ' + JSON.stringify(path.join(skillsDir, e)), { stdio: 'pipe' });
              removed++;
            }
          }
        } catch (e) {}

        try { execSync('rm -rf /tmp/openclaw', { stdio: 'pipe' }); removed++; } catch (e) {}

        console.log('Removed ' + removed + ' items');
      " || echo "  WARN: State wipe had errors (continuing)"

      # 1d. Deploy FantaCo backends (Helm)
      echo "  Deploying FantaCo backends..."
      echo "    Customer app..."
      apply_templates fantaco-app "$HELM_DIR/fantaco-app" "$NS" "${CUSTOMER_APP_TEMPLATES[@]}" || true
      echo "    Customer MCP..."
      apply_templates fantaco-mcp "$HELM_DIR/fantaco-mcp" "$NS" "${CUSTOMER_MCP_TEMPLATES[@]}" || true
      echo "    Sales-order app..."
      apply_templates fantaco-app "$HELM_DIR/fantaco-app" "$NS" "${SALESORDER_APP_TEMPLATES[@]}" || true
      echo "    Sales-order MCP..."
      apply_templates fantaco-mcp "$HELM_DIR/fantaco-mcp" "$NS" "${SALESORDER_MCP_TEMPLATES[@]}" || true
      echo "    Product app..."
      apply_templates fantaco-app "$HELM_DIR/fantaco-app" "$NS" "${PRODUCT_APP_TEMPLATES[@]}" || true
      echo "    Product MCP..."
      apply_templates fantaco-mcp "$HELM_DIR/fantaco-mcp" "$NS" "${PRODUCT_MCP_TEMPLATES[@]}" || true

      # 1d2. Inject Langfuse OTEL auth header into MCP deployments
      if [[ -f "${SCRIPT_DIR}/.state/${CLUSTER_GUID}/langfuse.env" ]]; then
        # shellcheck disable=SC1090
        source "${SCRIPT_DIR}/.state/${CLUSTER_GUID}/langfuse.env"
        LF_AUTH="Basic $(echo -n "${INIT_PUBLIC_KEY}:${INIT_SECRET_KEY}" | base64)"
        for MCP_DEP in mcp-customer mcp-product mcp-sales-order; do
          oc set env deployment/"$MCP_DEP" -n "$NS" \
            OTEL_EXPORTER_OTLP_TRACES_HEADERS="Authorization=${LF_AUTH}" \
            2>/dev/null || true
        done
      fi

      # 1e. Create new audience Route with unique hostname
      echo "  Creating audience Route..."
      oc apply -n "$NS" -f - <<EOF
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: audience
  labels:
    app: claw
    audience-route: "true"
  annotations:
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  host: ${AUDIENCE_HOST}
  to:
    kind: Service
    name: instance
    weight: 100
  port:
    targetPort: 18789
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
EOF

      # 1f. Ensure Langfuse proxy credential exists (for existing namespaces that
      #     were created before we added the langfuse credential to the Claw CR)
      if [[ -n "${LANGFUSE_PUBLIC_KEY:-}" && -n "${LANGFUSE_SECRET_KEY:-}" && -n "${LANGFUSE_ROUTE:-}" ]]; then
        LANGFUSE_BASIC_AUTH=$(echo -n "${LANGFUSE_PUBLIC_KEY}:${LANGFUSE_SECRET_KEY}" | base64)
        oc create secret generic langfuse-auth \
          --from-literal=basic-auth="$LANGFUSE_BASIC_AUTH" \
          -n "$NS" --dry-run=client -o yaml | oc apply -f - 2>/dev/null || true
        # Ensure Claw CR has the langfuse credential (check before patching to be idempotent)
        if ! oc get claw instance -n "$NS" -o jsonpath='{.spec.credentials[*].name}' 2>/dev/null | grep -q '\blangfuse\b'; then
          oc patch claw instance -n "$NS" --type=json -p \
            "[{\"op\":\"add\",\"path\":\"/spec/credentials/-\",\"value\":{\"name\":\"langfuse\",\"type\":\"apiKey\",\"domain\":\"${LANGFUSE_ROUTE}\",\"secretRef\":[{\"name\":\"langfuse-auth\",\"key\":\"basic-auth\"}],\"apiKey\":{\"header\":\"authorization\",\"valuePrefix\":\"Basic \"}}}]" \
            2>/dev/null || true
        fi
      fi

      # 1g. Set OTEL/Langfuse env vars + restart gateway
      # oc set env triggers a rollout automatically; when no env vars needed, fall back to oc rollout restart
      ENV_ARGS=()
      if [[ -n "${MLFLOW_OTEL_ENDPOINT:-}" ]]; then
        ENV_ARGS+=(
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="${MLFLOW_OTEL_ENDPOINT}"
          OTEL_EXPORTER_OTLP_TRACES_HEADERS="${MLFLOW_OTEL_HEADERS}"
          OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
          OTEL_EXPORTER_OTLP_TRACES_PROTOCOL="http/protobuf"
          OTEL_SERVICE_NAME="openclaw-${NS}"
          OTEL_RESOURCE_ATTRIBUTES="openclaw.namespace=${NS}"
          OTEL_SEMCONV_STABILITY_OPT_IN="gen_ai_latest_experimental"
        )
      fi
      if [[ "${OTEL_BACKEND:-}" == "Langfuse" ]]; then
        ENV_ARGS+=(
          LANGFUSE_BASE_URL="${LANGFUSE_URL}"
          LANGFUSE_TRACE_URL="${AUDIENCE_HOST}"
          LANGFUSE_PUBLIC_KEY-
          LANGFUSE_SECRET_KEY-
        )
        # Keys are explicitly REMOVED (trailing -) from gateway env vars.
        # Auth is handled by the claw-operator proxy via the langfuse-auth Secret.
      fi
      if [[ ${#ENV_ARGS[@]} -gt 0 ]]; then
        echo "  Setting ${#ENV_ARGS[@]} OTEL/Langfuse env vars + restarting gateway..."
        oc set env deployment/instance -n "$NS" -c gateway "${ENV_ARGS[@]}" 2>/dev/null || true
        echo "OTEL_PATCHED=true" >> "${PHASE1_TMPDIR}/${NS}.result"
      else
        echo "  Restarting gateway..."
        oc rollout restart deployment/instance -n "$NS"
      fi

      # 1h. Wait for rollout
      if oc rollout status deployment/instance -n "$NS" --timeout=120s 2>/dev/null; then
        echo "STATUS=success" >> "${PHASE1_TMPDIR}/${NS}.result"
      else
        echo "  WARN: Rollout did not complete within 120s."
        echo "STATUS=fail" >> "${PHASE1_TMPDIR}/${NS}.result"
      fi

      # 1i. Wait for FantaCo backend pods
      echo "  Waiting for FantaCo backend pods..."
      wait_for_pods "$NS" \
        "(fantaco-customer-main|postgresql-customer|mcp-customer|fantaco-product-main|postgresql-product|mcp-product|fantaco-sales-order-main|postgresql-salesorder|mcp-sales-order)" \
        9 "FantaCo backends"

      NS_ELAPSED=$(( $(date +%s) - NS_START_EPOCH ))
      echo "ELAPSED=${NS_ELAPSED}" >> "${PHASE1_TMPDIR}/${NS}.result"
      NS_MIN=$(( NS_ELAPSED / 60 ))
      NS_SEC=$(( NS_ELAPSED % 60 ))
      echo "  done: ${NS} (${NS_MIN}m ${NS_SEC}s)"

    } > "$LOG" 2>&1
  ) &
  PIDS+=($!)

  # Throttle: if pool is full, wait for the oldest job to finish
  if (( ${#PIDS[@]} >= MAX_PARALLEL )); then
    wait "${PIDS[0]}" 2>/dev/null || true
    PIDS=("${PIDS[@]:1}")
  fi
done

# Wait for remaining jobs
for pid in "${PIDS[@]}"; do
  wait "$pid" 2>/dev/null || true
done

# ── Collect results ──────────────────────────────────────────────────
echo ""
echo -e "${BOLD}--- Phase 1 Results ---${RESET}"
for NS in "${NAMESPACES[@]}"; do
  RESULT_FILE="${PHASE1_TMPDIR}/${NS}.result"
  NS_STATUS="" NS_URL="" NS_HOST="" NS_LABEL="" NS_OTEL="" NS_ELAPSED=""

  if [[ -f "$RESULT_FILE" ]]; then
    while IFS='=' read -r key value; do
      case "$key" in
        STATUS) NS_STATUS="$value" ;;
        URL) NS_URL="$value" ;;
        HOST) NS_HOST="$value" ;;
        LABEL) NS_LABEL="$value" ;;
        OTEL_PATCHED) NS_OTEL="$value" ;;
        ELAPSED) NS_ELAPSED="$value" ;;
      esac
    done < "$RESULT_FILE"
  fi

  if [[ "$NS_STATUS" == "success" ]]; then
    SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
    AUDIENCE_URLS+=("$NS_URL")
    AUDIENCE_HOSTS+=("$NS_HOST")
    AUDIENCE_LABELS+=("$NS_LABEL")
    NS_MIN=$(( ${NS_ELAPSED:-0} / 60 ))
    NS_SEC=$(( ${NS_ELAPSED:-0} % 60 ))
    echo -e "  ${GREEN}✓${RESET} ${NS}  ${DIM}(${NS_MIN}m ${NS_SEC}s)${RESET}"
  else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    echo -e "  ${RED}✗${RESET} ${NS}"
    # Print log for failed namespaces so the user can debug
    if [[ -f "${PHASE1_TMPDIR}/${NS}.log" ]]; then
      sed 's/^/    /' "${PHASE1_TMPDIR}/${NS}.log"
    fi
  fi

  if [[ "$NS_OTEL" == "true" ]]; then
    OTEL_PATCHED=true
  fi
done

rm -rf "$PHASE1_TMPDIR"
echo ""

# ══════════════════════════════════════════════════════════════════════
# Phase 2: Inject MCP endpoints (patch Claw CR + NetworkPolicy)
# ══════════════════════════════════════════════════════════════════════
echo -e "${BOLD}--- Injecting MCP endpoints ---${RESET}"
for NS in "${NAMESPACES[@]}"; do
  echo "  $NS: patching Claw CR (customer + product + sales-order)..."
  oc patch claw instance -n "$NS" --type=merge -p \
    '{"spec":{"mcpServers":{"customer":{"url":"http://mcp-customer-service:9001/mcp","transport":"streamable-http"},"product":{"url":"http://mcp-product-service:9003/mcp","transport":"streamable-http"},"sales-order":{"url":"http://mcp-sales-order-service:9004/mcp","transport":"streamable-http"}}}}' \
    2>&1 | sed 's/^/    /' || true

  echo "  $NS: applying NetworkPolicy (proxy -> MCP services)..."
  cat <<'NETPOL' | oc apply -n "$NS" -f - 2>&1 | sed 's/^/    /'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-to-mcp
  labels:
    app: fantaco-mcp
spec:
  podSelector:
    matchLabels:
      app: claw-proxy
      claw.sandbox.redhat.com/instance: instance
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mcp-customer
      ports:
        - port: 9001
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: mcp-product
      ports:
        - port: 9003
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: mcp-sales-order
      ports:
        - port: 9004
          protocol: TCP
NETPOL

  # OTEL / Langfuse / Prometheus NetworkPolicies + ServiceMonitor
  if [[ -n "${MLFLOW_ROUTE:-}" ]]; then
    oc apply -n "$NS" -f - <<'NETPOL_EOF' 2>/dev/null
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-instance-to-mlflow
spec:
  podSelector:
    matchLabels:
      app: claw
      claw.sandbox.redhat.com/instance: instance
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: mlflow
    ports:
    - port: 5000
      protocol: TCP
NETPOL_EOF
  fi
  # Langfuse: no direct NetworkPolicy needed — the claw-operator proxy handles
  # Langfuse traffic via the external route (credential injection by proxy).
  # Clean up legacy direct-access policy if it exists.
  oc delete networkpolicy allow-instance-to-langfuse -n "$NS" 2>/dev/null || true
  # Prometheus scraping NetworkPolicy + ServiceMonitor (idempotent, always applied)
  oc apply -n "$NS" -f - <<'NETPOL_EOF' 2>/dev/null
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape
spec:
  podSelector:
    matchLabels:
      app: claw
      claw.sandbox.redhat.com/instance: instance
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
    ports:
    - port: 18789
      protocol: TCP
  policyTypes:
  - Ingress
NETPOL_EOF
  oc apply -n "$NS" -f - <<'SM_EOF' 2>/dev/null
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openclaw-gateway
spec:
  endpoints:
  - interval: 30s
    port: gateway
    path: /api/diagnostics/prometheus
    authorization:
      type: Bearer
      credentials:
        name: instance-gateway-token
        key: token
  selector:
    matchLabels:
      app: claw
      claw.sandbox.redhat.com/instance: instance
SM_EOF
done
echo "  NetworkPolicies + Prometheus ServiceMonitors: applied to all namespaces"
echo ""

# ══════════════════════════════════════════════════════════════════════
# Phase 3: Install plugins + combined JSON repatch
#
# After Phase 1's restart, install plugin packages and write ALL config
# in one shot per namespace via post-restart-repatch.sh.
# ══════════════════════════════════════════════════════════════════════
echo -e "${BOLD}--- Installing plugins + patching config ---${RESET}"

# Detect state for summary
DIAG_PATCHED=false
MODEL_PATCHED=false
if [[ -n "$LLM_PROVIDER" ]]; then
  MODEL_PATCHED=true
fi

PLUGINS_DIR="${SCRIPT_DIR}/../claw_plugins"
PLUGINS_DEST="/home/node/.openclaw/extensions"

for NS in "${NAMESPACES[@]}"; do
  wait_for_exec_ready "$NS" || continue

  # 3a. Copy langfuse-tracer plugin files BEFORE repatch (so repatch detects them)
  if [[ -n "${LANGFUSE_PUBLIC_KEY:-}" && -n "${LANGFUSE_SECRET_KEY:-}" && -d "$PLUGINS_DIR/langfuse-tracer" ]]; then
    POD=$(oc get pods -n "$NS" -l claw.sandbox.redhat.com/instance=instance --no-headers 2>/dev/null \
      | grep "^instance-" | grep -v proxy | grep -v device-pairing | grep "Running" | awk '{print $1}' | head -1)
    if [[ -n "$POD" ]]; then
      oc exec "$POD" -n "$NS" -c gateway -- mkdir -p "${PLUGINS_DEST}/langfuse-tracer" 2>/dev/null
      PLUGIN_OK=true
      for PFILE in index.js openclaw.plugin.json; do
        if ! oc cp "$PLUGINS_DIR/langfuse-tracer/$PFILE" "$POD:${PLUGINS_DEST}/langfuse-tracer/$PFILE" -n "$NS" -c gateway 2>/dev/null; then
          echo -e "  ${YELLOW}⚠${RESET} $NS: langfuse-tracer/$PFILE copy failed"
          PLUGIN_OK=false
        fi
      done
      if [[ "$PLUGIN_OK" == "true" ]]; then
        echo -e "  ${GREEN}✓${RESET} $NS: langfuse-tracer files copied"
      fi
    fi
  fi

  # 3b. Install prometheus plugin (ServiceMonitor always created above)
  DIAG_PATCHED=true
  oc exec deployment/instance -n "$NS" -c gateway -- \
    node /app/dist/index.js plugins install @openclaw/diagnostics-prometheus@2026.5.26 2>&1 \
    | grep -E "^(Installed|Already|Error)" || true

  # 3c. Install diagnostics-otel plugin (if MLflow deployed)
  if [[ -n "$MLFLOW_OTEL_ENDPOINT" ]]; then
    oc exec deployment/instance -n "$NS" -c gateway -- \
      node /app/dist/index.js plugins install @openclaw/diagnostics-otel@2026.5.26 2>&1 \
      | grep -E "^(Installed|Already|Error)" || true
  fi

  # 3d. Combined JSON repatch (model, allowedOrigins, diagnostics, all plugins)
  "${SCRIPT_DIR}/post-restart-repatch.sh" --site "${SITE_NAME}" "$NS"
done
echo ""

# ══════════════════════════════════════════════════════════════════════
# Phase 4: Inject enterprise persona, skills, and agent instructions
#           (must be LAST — after final restart, since restarts wipe PVC state)
# ══════════════════════════════════════════════════════════════════════
echo -e "${BOLD}--- Injecting enterprise persona + skills ---${RESET}"
SKILLS_INJECTED=0
for NS in "${NAMESPACES[@]}"; do
  POD=$(oc get pods -n "$NS" -l claw.sandbox.redhat.com/instance=instance --no-headers 2>/dev/null \
    | grep "^instance-" | grep -v proxy | grep -v device-pairing | grep "Running" | awk '{print $1}' | head -1)

  if [[ -z "$POD" ]]; then
    echo -e "  ${YELLOW}$NS: no running gateway pod — skipping${RESET}"
    continue
  fi

  # 4a. Pre-fill IDENTITY.md (prevents bootstrap questionnaire)
  oc cp "$SCRIPT_DIR/workspace-templates/IDENTITY.md" "$POD:/home/node/.openclaw/workspace/IDENTITY.md" -n "$NS" -c gateway \
    2>/dev/null && echo -e "  ${GREEN}✓${RESET} $NS: IDENTITY.md pre-filled" \
    || echo -e "  ${YELLOW}⚠${RESET} $NS: IDENTITY.md write failed"

  # 4a2. Pre-fill SOUL.md (sales assistant personality)
  oc cp "$SCRIPT_DIR/workspace-templates/SOUL.md" "$POD:/home/node/.openclaw/workspace/SOUL.md" -n "$NS" -c gateway \
    2>/dev/null && echo -e "  ${GREEN}✓${RESET} $NS: SOUL.md pre-filled" \
    || echo -e "  ${YELLOW}⚠${RESET} $NS: SOUL.md write failed"

  # 4b. Append enterprise assistant instructions to AGENTS.md
  AGENTS_APPEND=$(cat "$SCRIPT_DIR/workspace-templates/AGENTS.md.append")
  oc exec "$POD" -n "$NS" -c gateway -- node -e "
    const fs = require('fs');
    const f = '/home/node/.openclaw/workspace/AGENTS.md';
    let content = fs.readFileSync(f, 'utf8');
    if (!content.includes('Enterprise assistant')) {
      content += $(printf '%s' "$AGENTS_APPEND" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))');
      fs.writeFileSync(f, content);
    }
  " 2>/dev/null && echo -e "  ${GREEN}✓${RESET} $NS: AGENTS.md patched" \
    || echo -e "  ${YELLOW}⚠${RESET} $NS: AGENTS.md patch failed"

  # 4c. Replace TOOLS.md with MCP server guidance
  oc cp "$SCRIPT_DIR/workspace-templates/TOOLS.md" "$POD:/home/node/.openclaw/workspace/TOOLS.md" -n "$NS" -c gateway \
    2>/dev/null && echo -e "  ${GREEN}✓${RESET} $NS: TOOLS.md updated" \
    || echo -e "  ${YELLOW}⚠${RESET} $NS: TOOLS.md write failed"

  # 4d. Inject enterprise skills
  for SKILL in "${SKILLS[@]}"; do
    if [[ ! -f "$SKILLS_DIR/$SKILL/SKILL.md" ]]; then
      echo -e "  ${YELLOW}$NS: skill not found locally: $SKILL${RESET}"
      continue
    fi
    oc exec "$POD" -n "$NS" -c gateway -- mkdir -p "${SKILLS_DEST}/${SKILL}" 2>/dev/null
    if oc cp "$SKILLS_DIR/$SKILL/SKILL.md" "$POD:${SKILLS_DEST}/${SKILL}/SKILL.md" -n "$NS" -c gateway 2>/dev/null; then
      echo -e "  ${GREEN}✓${RESET} $NS: $SKILL injected"
      SKILLS_INJECTED=$((SKILLS_INJECTED + 1))
    else
      echo -e "  ${YELLOW}⚠${RESET} $NS: $SKILL injection failed"
    fi
  done
done
echo "  Injected $SKILLS_INJECTED skill(s) across ${#NAMESPACES[@]} namespace(s)"
echo ""

# ══════════════════════════════════════════════════════════════════════
# Phase 5: Disable heartbeat (prevents idle LLM token consumption)
# ══════════════════════════════════════════════════════════════════════
echo -e "${BOLD}--- Disabling heartbeat ---${RESET}"
"${SCRIPT_DIR}/manage-heartbeat.sh" disable ${START:+$START} ${END:+$END}
echo ""

# ══════════════════════════════════════════════════════════════════════
# Final cleanup: Reset trace backends
# ══════════════════════════════════════════════════════════════════════
# Runs AFTER all restarts/OTEL re-patching so startup traces are also wiped.

# Reset MLflow traces
MLFLOW_ROUTE_CHECK=$(oc get route mlflow -n mlflow -o jsonpath='{.spec.host}' 2>/dev/null || true)
if [[ -n "$MLFLOW_ROUTE_CHECK" ]]; then
  echo -e "${BOLD}--- Resetting MLflow traces ---${RESET}"
  MLFLOW_RESET_URL="https://${MLFLOW_ROUTE_CHECK}"

  # Get experiment ID
  RESET_EXP_ID=$(curl -sk "${MLFLOW_RESET_URL}/api/2.0/mlflow/experiments/get-by-name?experiment_name=openclaw-traces" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['experiment']['experiment_id'])" 2>/dev/null || echo "")

  if [[ -n "$RESET_EXP_ID" ]]; then
    # Brief pause to let in-flight OTEL exports from gateway restarts land
    sleep 3
    CURRENT_TIME_MS=$(($(date +%s) * 1000 + 5000))
    DELETE_RESULT=$(curl -sk -X POST "${MLFLOW_RESET_URL}/api/2.0/mlflow/traces/delete-traces" \
      -H "Content-Type: application/json" \
      -d "{\"experiment_id\":\"${RESET_EXP_ID}\",\"max_timestamp_millis\":${CURRENT_TIME_MS},\"max_traces\":999999}" \
      2>/dev/null)
    TRACES_DELETED=$(echo "$DELETE_RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('traces_deleted',0))" 2>/dev/null || echo "0")
    echo -e "  ${GREEN}Deleted ${TRACES_DELETED} traces from experiment ${RESET_EXP_ID}${RESET}"
  else
    echo -e "  ${YELLOW}Could not find openclaw-traces experiment — skipping${RESET}"
  fi
  echo ""
fi

# Reset Langfuse traces
LANGFUSE_ROUTE_CHECK=$(oc get route langfuse -n langfuse -o jsonpath='{.spec.host}' 2>/dev/null || true)
if [[ -n "$LANGFUSE_ROUTE_CHECK" && -n "${LANGFUSE_PUBLIC_KEY:-}" && -n "${LANGFUSE_SECRET_KEY:-}" ]]; then
  echo -e "${BOLD}--- Resetting Langfuse traces ---${RESET}"
  LANGFUSE_RESET_URL="https://${LANGFUSE_ROUTE_CHECK}"

  # Brief pause to let in-flight OTEL exports land
  sleep 3

  # Use Langfuse API to count existing traces
  TRACE_COUNT=$(curl -sk -u "${LANGFUSE_PUBLIC_KEY}:${LANGFUSE_SECRET_KEY}" \
    "${LANGFUSE_RESET_URL}/api/public/traces?limit=1" \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('meta',{}).get('totalItems',0))" 2>/dev/null || echo "0")

  if [[ "$TRACE_COUNT" -gt 0 ]]; then
    # Delete traces via ClickHouse (Langfuse has no bulk delete API)
    CH_POD=$(oc get pod -n langfuse -l app.kubernetes.io/component=clickhouse -o name 2>/dev/null | head -1)
    if [[ -n "$CH_POD" ]]; then
      CH_PASS=$(oc get secret langfuse-clickhouse-auth -n langfuse -o jsonpath='{.data.password}' 2>/dev/null | base64 -d)
      oc exec -n langfuse "${CH_POD}" -- clickhouse-client \
        --user default --password "${CH_PASS}" \
        --query "ALTER TABLE traces DELETE WHERE 1=1" 2>/dev/null || true
      oc exec -n langfuse "${CH_POD}" -- clickhouse-client \
        --user default --password "${CH_PASS}" \
        --query "ALTER TABLE observations DELETE WHERE 1=1" 2>/dev/null || true
      oc exec -n langfuse "${CH_POD}" -- clickhouse-client \
        --user default --password "${CH_PASS}" \
        --query "ALTER TABLE scores DELETE WHERE 1=1" 2>/dev/null || true
      echo -e "  ${GREEN}Cleared ${TRACE_COUNT} traces from Langfuse ClickHouse${RESET}"
    else
      echo -e "  ${YELLOW}ClickHouse pod not found — ${TRACE_COUNT} traces remain${RESET}"
      echo "  Traces will accumulate; filter by timestamp in the Langfuse UI"
    fi
  else
    echo -e "  ${GREEN}No existing traces to clear${RESET}"
  fi
  echo ""
fi

# ══════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════
echo ""
SCRIPT_ELAPSED=$(( $(date +%s) - SCRIPT_START_EPOCH ))
SCRIPT_MIN=$(( SCRIPT_ELAPSED / 60 ))
SCRIPT_SEC=$(( SCRIPT_ELAPSED % 60 ))

echo -e "${BOLD}============================================${RESET}"
echo -e "${BOLD}  Audience Reset Complete  ${DIM}(${SCRIPT_MIN}m ${SCRIPT_SEC}s total)${RESET}"
echo -e "${BOLD}============================================${RESET}"
echo ""
echo -e "  Succeeded: ${GREEN}${SUCCESS_COUNT}${RESET}"
if [[ $FAIL_COUNT -gt 0 ]]; then
  echo -e "  Failed:    ${RED}${FAIL_COUNT}${RESET}"
fi
if [[ "$MODEL_PATCHED" == "true" ]]; then
  echo "  Model:     re-patched from .env"
fi
if [[ "$DIAG_PATCHED" == "true" ]]; then
  echo "  Prometheus: re-patched"
fi
if [[ "${OTEL_PATCHED:-false}" == "true" ]]; then
  echo "  OTEL Traces: ${OTEL_BACKEND} (re-patched)"
fi
echo "  Skills:    ${SKILLS_INJECTED} injected"
echo ""

if [[ ${#AUDIENCE_URLS[@]} -gt 0 ]]; then
  echo -e "  Audience routes: ${GREEN}${#AUDIENCE_URLS[@]}${RESET} created (code: ${CYAN}${AUDIENCE_CODE}${RESET})"
  echo ""
  echo -e "  ${BOLD}Next:${RESET} Run ${CYAN}./update-broker.sh --rotate-status-key${RESET} to publish to ${BROKER_DOMAIN}"
  echo -e "  ${DIM}(requires AWS session — run 'aws login' first if needed)${RESET}"
  echo ""
fi
echo -e "  ${DIM}Admin URLs (stable): oc get route instance -n <namespace>${RESET}"
echo ""
