#!/usr/bin/env bash
# post-restart-repatch.sh — Re-patch openclaw.json after a gateway restart
#
# Every `oc rollout restart` causes the claw-operator to re-seed openclaw.json
# from its ConfigMap, wiping custom config (allowedOrigins, model, plugins,
# diagnostics). This script re-applies all config so it survives restarts.
#
# Usage:
#   ./post-restart-repatch.sh <namespace>    # single namespace
#   ./post-restart-repatch.sh 1 5            # agentic-user1 through agentic-user5
#   ./post-restart-repatch.sh 3              # just agentic-user3
#
# What it patches:
#   1. allowedOrigins — audience route host + broker domain
#   2. Model — google/{GEMINI_MODEL} or openai/{LLM_MODEL_NAME} from .env
#   3. diagnostics.otel — full OTEL config block (if diagnostics-otel plugin installed)
#   4. diagnostics-prometheus plugin — only if ServiceMonitor exists
#   5. diagnostics-otel plugin — plugins.allow + plugins.entries
#   6. langfuse-tracer plugin — only if Langfuse keys in .env + plugin files on disk
#   7. Custom proxy domains — re-applies domains from .state/<cluster-guid>/custom-proxy-domains.csv
#
# Requires: .env sourced for LLM_PROVIDER, GEMINI_MODEL, LLM_MODEL_NAME, BROKER_DOMAIN
# Does NOT restart the gateway — caller is responsible for restart timing.

set -euo pipefail

NAMESPACE_PREFIX="${NAMESPACE_PREFIX:-agentic-user}"

# --- Colors ---
YELLOW='\033[1;33m'
RESET='\033[0m'

# Wait for gateway to be exec-ready after restart
wait_for_exec_ready() {
  local ns=$1
  local max_wait=${2:-30}
  for _attempt in $(seq 1 "$max_wait"); do
    if oc exec deployment/instance -n "$ns" -c gateway -- node -e "console.log('ready')" &>/dev/null; then
      return 0
    fi
    sleep 2
  done
  echo -e "  ${YELLOW}⚠${RESET} $ns: gateway not exec-ready after $((max_wait * 2))s"
  return 1
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLUSTER_GUID=$(oc cluster-info 2>/dev/null | head -1 | sed 's|.*api\.ocp\.\([^.]*\)\..*|\1|')
if [[ -z "$CLUSTER_GUID" ]]; then
  echo "Error: could not extract cluster GUID from 'oc cluster-info'" >&2
  exit 1
fi
ENV_FILE="${SCRIPT_DIR}/../.env"

# ── Source .env ────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi
# Source Langfuse keys from cluster state (generated by deploy-traces-langfuse.sh)
LANGFUSE_STATE="${SCRIPT_DIR}/.state/${CLUSTER_GUID}/langfuse.env"
if [[ -f "$LANGFUSE_STATE" ]]; then
  # shellcheck disable=SC1090
  source "$LANGFUSE_STATE"
  LANGFUSE_PUBLIC_KEY="${INIT_PUBLIC_KEY:-}"
  LANGFUSE_SECRET_KEY="${INIT_SECRET_KEY:-}"
fi
LLM_PROVIDER="${LLM_PROVIDER:-}"
STUDENT_OPENCLAW_PASSWORD="${STUDENT_OPENCLAW_PASSWORD:-}"
BROKER_DOMAIN="${BROKER_DOMAIN:-yougetaclaw.com}"

# ── Argument parsing ──────────────────────────────────────────────
NAMESPACES=()
if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <namespace>       # single namespace by name"
  echo "       $0 <start> [end]     # agentic-user<start> through agentic-user<end>"
  exit 1
elif [[ $# -eq 1 && ! "$1" =~ ^[0-9]+$ ]]; then
  # Single namespace name (e.g. "agentic-user3" or current NS)
  NAMESPACES+=("$1")
elif [[ $# -le 2 ]]; then
  START=$1
  END=${2:-$START}
  if [[ $START -gt $END ]]; then
    echo "Error: start ($START) must be <= end ($END)"
    exit 1
  fi
  for i in $(seq "$START" "$END"); do
    NAMESPACES+=("${NAMESPACE_PREFIX}${i}")
  done
else
  echo "Usage: $0 <namespace>       # single namespace by name"
  echo "       $0 <start> [end]     # agentic-user<start> through agentic-user<end>"
  exit 1
fi

# ── Determine model config ────────────────────────────────────────
MODEL_KEY=""
MODEL_ALIAS=""
MODEL_PROVIDER_PATCH=""

if [[ "$LLM_PROVIDER" == "gcp" && -n "${GEMINI_MODEL:-}" ]]; then
  MODEL_KEY="google/${GEMINI_MODEL}"
  MODEL_ALIAS="${GEMINI_MODEL}"
elif [[ "$LLM_PROVIDER" == "litellm" && -n "${LLM_MODEL_NAME:-}" ]]; then
  MODEL_KEY="openai/${LLM_MODEL_NAME}"
  MODEL_ALIAS="${LLM_MODEL_NAME}"
  # Derive token limits based on model name
  if [[ "$LLM_MODEL_NAME" == claude-* ]]; then
    MODEL_CONTEXT_WINDOW=200000; MODEL_CONTEXT_TOKENS=180000; MODEL_MAX_TOKENS=8192
  elif [[ "$LLM_MODEL_NAME" == "qwen3-14b" ]]; then
    MODEL_CONTEXT_WINDOW=40960; MODEL_CONTEXT_TOKENS=32768; MODEL_MAX_TOKENS=4096
  else
    MODEL_CONTEXT_WINDOW=128000; MODEL_CONTEXT_TOKENS=128000; MODEL_MAX_TOKENS=16384
  fi
  MODEL_PROVIDER_PATCH="
    c.models = c.models || {};
    c.models.providers = c.models.providers || {};
    c.models.providers.openai = c.models.providers.openai || {};
    var p = c.models.providers.openai;
    p.contextWindow = ${MODEL_CONTEXT_WINDOW};
    p.contextTokens = ${MODEL_CONTEXT_TOKENS};
    p.maxTokens = ${MODEL_MAX_TOKENS};
    p.models = [{
      id: '${LLM_MODEL_NAME}', name: '${LLM_MODEL_NAME}',
      api: 'openai-completions', reasoning: false, input: ['text'],
      contextWindow: ${MODEL_CONTEXT_WINDOW}, contextTokens: ${MODEL_CONTEXT_TOKENS},
      maxTokens: ${MODEL_MAX_TOKENS},
      compat: { maxTokensField: 'max_tokens', supportsStore: false,
        supportsPromptCacheKey: false, supportsReasoningEffort: false,
        supportsDeveloperRole: false }
    }];
  "
elif [[ "$LLM_PROVIDER" == "openrouter" && -n "${OPENROUTER_MODEL:-}" ]]; then
  MODEL_KEY="openai/${OPENROUTER_MODEL}"
  MODEL_ALIAS="${OPENROUTER_MODEL}"
  MODEL_PROVIDER_PATCH="
    c.models = c.models || {};
    c.models.providers = c.models.providers || {};
    c.models.providers.openai = c.models.providers.openai || {};
    var p = c.models.providers.openai;
    p.baseUrl = 'https://openrouter.ai/api/v1';
    p.apiKey = '${OPENROUTER_API_KEY}';
    p.contextWindow = 131072;
    p.contextTokens = 131072;
    p.maxTokens = 8192;
    p.models = [{
      id: '${OPENROUTER_MODEL}', name: '${OPENROUTER_MODEL}',
      api: 'openai-completions', reasoning: true, input: ['text'],
      contextWindow: 131072, contextTokens: 131072, maxTokens: 8192,
      compat: { maxTokensField: 'max_tokens', supportsStore: false,
        supportsPromptCacheKey: false, supportsReasoningEffort: false,
        supportsDeveloperRole: false }
    }];
  "
fi

# ── Detect trace backends ─────────────────────────────────────────
# diagnostics-otel always targets MLflow (if deployed).
# langfuse-tracer handles Langfuse traces via REST API (not OTEL).
OTEL_ENDPOINT=""
OTEL_HEADERS=""

# Detect MLflow (diagnostics-otel target)
MLFLOW_ROUTE=$(oc get route mlflow -n mlflow -o jsonpath='{.spec.host}' 2>/dev/null || true)
if [[ -n "$MLFLOW_ROUTE" ]]; then
  MLFLOW_INTERNAL_URL="http://mlflow-mlflow.mlflow.svc.cluster.local:5000"
  MLFLOW_URL="https://${MLFLOW_ROUTE}"
  EXPERIMENT_ID=$(curl -sk "${MLFLOW_URL}/api/2.0/mlflow/experiments/get-by-name?experiment_name=openclaw-traces" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['experiment']['experiment_id'])" 2>/dev/null || echo "1")
  OTEL_ENDPOINT="${MLFLOW_INTERNAL_URL}/v1/traces"
  OTEL_HEADERS="x-mlflow-experiment-id=${EXPERIMENT_ID}"
fi

# Detect Langfuse (langfuse-tracer plugin — does NOT use OTEL_ENDPOINT)
LANGFUSE_ROUTE=$(oc get route langfuse -n langfuse -o jsonpath='{.spec.host}' 2>/dev/null || true)

# ── Resolve gateway password ──────────────────────────────────────
# Try .env first, then fall back to reading the claw-password secret from the first namespace
GATEWAY_PASSWORD="${STUDENT_OPENCLAW_PASSWORD:-}"
if [[ -z "$GATEWAY_PASSWORD" && ${#NAMESPACES[@]} -gt 0 ]]; then
  GATEWAY_PASSWORD=$(oc get secret claw-password -n "${NAMESPACES[0]}" -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null || true)
fi

# ── Per-namespace re-patch ────────────────────────────────────────
for NS in "${NAMESPACES[@]}"; do
  # Verify gateway pod exists
  POD=$(oc get pods -n "$NS" -l claw.sandbox.redhat.com/instance=instance -l app=claw --no-headers -o custom-columns=NAME:.metadata.name 2>/dev/null | head -1)
  if [[ -z "$POD" ]]; then
    echo "  WARN: No gateway pod in $NS — skipping re-patch"
    continue
  fi

  # Wait for container to be exec-ready (rollout status can return before node is up)
  wait_for_exec_ready "$NS" || continue

  # Read audience route host for allowedOrigins
  AUDIENCE_HOST=$(oc get route audience -n "$NS" -o jsonpath='{.spec.host}' 2>/dev/null || true)
  PUB_HOST=""
  if [[ -n "$AUDIENCE_HOST" ]]; then
    PUB_HOST="${AUDIENCE_HOST%%.*}.${BROKER_DOMAIN}"
  fi

  # Check if ServiceMonitor exists (prometheus was enabled)
  HAS_PROMETHEUS="false"
  if oc get servicemonitor openclaw-gateway -n "$NS" &>/dev/null; then
    HAS_PROMETHEUS="true"
  fi

  echo "  $NS: re-patching config..."

  # Single piped node script that patches everything at once
  # Uses piped stdin to avoid `!` escaping issues with `oc exec -- node -e`
  cat <<REPATCH_EOF | oc exec -i deployment/instance -n "$NS" -c gateway -- node 2>/dev/null
var fs = require("fs");
var f = "/home/node/.openclaw/openclaw.json";
var c = JSON.parse(fs.readFileSync(f));

// 1. allowedOrigins
if ("${AUDIENCE_HOST}") {
  c.gateway = c.gateway || {};
  c.gateway.controlUi = c.gateway.controlUi || {};
  var origins = c.gateway.controlUi.allowedOrigins || [];
  ["https://${AUDIENCE_HOST}", "https://${PUB_HOST}"].forEach(function(o) {
    if (o && o !== "https://" && origins.indexOf(o) === -1) origins.push(o);
  });
  c.gateway.controlUi.allowedOrigins = origins;
}

// 1b. Gateway password (operator sets auth.mode but not the actual password)
if ("${GATEWAY_PASSWORD}") {
  c.gateway = c.gateway || {};
  c.gateway.password = "${GATEWAY_PASSWORD}";
}

// 2. Model
if ("${MODEL_KEY}") {
  c.agents = c.agents || {};
  c.agents.defaults = c.agents.defaults || {};
  c.agents.defaults.models = c.agents.defaults.models || {};
  c.agents.defaults.model = c.agents.defaults.model || {};
  c.agents.defaults.models["${MODEL_KEY}"] = {alias: "${MODEL_ALIAS}"};
  c.agents.defaults.model.primary = "${MODEL_KEY}";
  ${MODEL_PROVIDER_PATCH}
}

// 3. diagnostics.otel
c.diagnostics = c.diagnostics || {};
c.diagnostics.enabled = true;
if ("${OTEL_ENDPOINT}") {
  c.diagnostics.otel = {
    enabled: true,
    protocol: "http/protobuf",
    traces: true,
    metrics: false,
    logs: false,
    sampleRate: 1,
    captureContent: {
      inputMessages: true,
      outputMessages: true,
      toolInputs: true,
      toolOutputs: true,
      systemPrompt: false
    }
  };
  c.env = c.env || {};
  c.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "${OTEL_ENDPOINT}";
  c.env.OTEL_EXPORTER_OTLP_TRACES_HEADERS = "${OTEL_HEADERS}";
}

// 4. diagnostics-prometheus plugin (only if ServiceMonitor exists)
c.plugins = c.plugins || {};
c.plugins.allow = c.plugins.allow || [];
c.plugins.entries = c.plugins.entries || {};
if ("${HAS_PROMETHEUS}" === "true") {
  if (c.plugins.allow.indexOf("diagnostics-prometheus") === -1) c.plugins.allow.push("diagnostics-prometheus");
  c.plugins.entries["diagnostics-prometheus"] = { enabled: true };
}

// 5. diagnostics-otel plugin (if OTEL backend detected)
if ("${OTEL_ENDPOINT}") {
  if (c.plugins.allow.indexOf("diagnostics-otel") === -1) c.plugins.allow.push("diagnostics-otel");
  c.plugins.entries["diagnostics-otel"] = {
    enabled: true,
    hooks: { allowConversationAccess: true }
  };
}

// 6. langfuse-tracer plugin (if Langfuse deployed and plugin files exist on disk)
//    Auth is handled by the claw-operator proxy — keys are NOT in the gateway pod
if ("${LANGFUSE_ROUTE}") {
  try {
    fs.statSync("/home/node/.openclaw/extensions/langfuse-tracer/index.js");
    if (c.plugins.allow.indexOf("langfuse-tracer") === -1) c.plugins.allow.push("langfuse-tracer");
    c.plugins.entries["langfuse-tracer"] = {
      enabled: true,
      hooks: { allowConversationAccess: true }
    };
  } catch(e) { /* plugin files not present — skip */ }
}

fs.writeFileSync(f, JSON.stringify(c, null, 2));
console.log("ok");
REPATCH_EOF
  echo "    done"
done

# ── 7. Re-apply custom proxy domains (global — all namespaces) ──────
# State file format: domain,action,paths(colon-separated),timestamp
CUSTOM_DOMAINS_FILE="${SCRIPT_DIR}/.state/${CLUSTER_GUID}/custom-proxy-domains.csv"
if [[ -f "$CUSTOM_DOMAINS_FILE" ]] && command -v jq &>/dev/null; then
  for NS in "${NAMESPACES[@]}"; do
    CURRENT=$(oc get configmap instance-proxy-config -n "$NS" \
      -o jsonpath='{.data.proxy-config\.json}' 2>/dev/null || true)
    [[ -z "$CURRENT" ]] && continue

    UPDATED="$CURRENT"
    CHANGED=false
    while IFS=',' read -r domain action paths _ts; do
      [[ -z "$domain" ]] && continue
      # Remove existing entry for this domain so we can replace it
      EXISTS=$(echo "$UPDATED" | jq -r --arg d "$domain" '.routes[] | select(.domain == $d) | .domain' 2>/dev/null || true)
      if [[ -n "$EXISTS" ]]; then
        UPDATED=$(echo "$UPDATED" | jq --arg d "$domain" '.routes |= map(select(.domain != $d))')
      fi
      # Build route JSON based on action type
      if [[ "$action" == "proxy" && -n "$paths" ]]; then
        PATHS_JSON=$(echo "$paths" | tr ':' '\n' | jq -R '{path: .}' | jq -s '.')
        ROUTE=$(jq -n --arg d "$domain" --argjson p "$PATHS_JSON" \
          '{"domain": $d, "action": "proxy", "paths": $p}')
      else
        ROUTE=$(jq -n --arg d "$domain" '{"domain": $d, "action": "passthrough"}')
      fi
      UPDATED=$(echo "$UPDATED" | jq --argjson r "$ROUTE" '.routes += [$r]')
      CHANGED=true
    done < "$CUSTOM_DOMAINS_FILE"

    if [[ "$CHANGED" == "true" ]]; then
      ESCAPED=$(echo "$UPDATED" | jq -c '.' | jq -Rs '.')
      oc patch configmap instance-proxy-config -n "$NS" \
        --type merge -p "{\"data\":{\"proxy-config.json\":${ESCAPED}}}" 2>/dev/null
      echo "  $NS: re-applied custom proxy domains"
    fi
  done
fi
