{{- if .Values.hrPolicySearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fantaco-hr-policy-search-secret
  labels:
    app: {{ .Values.hrPolicySearch.name }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.hrPolicySearch.secret.llmApiKey | quote }}
{{- end }}
