{{- if .Values.postgresql.hrRecruiting.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.hrRecruiting.service.name }}
  labels:
    app: {{ .Values.postgresql.hrRecruiting.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.hrRecruiting.service.port }}
      targetPort: pg-hr-recruit
      protocol: TCP
      name: pg-hr-recruit
  selector:
    app: {{ .Values.postgresql.hrRecruiting.name }}
{{- end }}
