{{- if .Values.salesorder.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fantaco-salesorder-secret
type: Opaque
stringData:
  database.password: {{ .Values.salesorder.database.password | quote }}
{{- end }}
