{{- if .Values.salesPolicySearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fantaco-sales-policy-search-secret
  labels:
    app: {{ .Values.salesPolicySearch.name }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.salesPolicySearch.secret.llmApiKey | quote }}
{{- end }}
