apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-sales-order
  labels:
    app: mcp-sales-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-sales-order
  template:
    metadata:
      labels:
        app: mcp-sales-order
    spec:
      containers:
      - name: mcp-server
        image: docker.io/burrsutter/mcp-server-sales-order:1.0.0
        imagePullPolicy: Always
        env:
        - name: SALES_ORDER_API_BASE_URL
          value: http://fantaco-sales-order-service:8084
        ports:
        - containerPort: 9003
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
