-- FantaCo HR - Seed Data (Happiness Herders & Harmonious Hijinks Department)
-- Jobs: 3 open, 1 filled, 1 closed — aligned with bespoke office wares + Fabulous Benefits lore
-- Applications: spread across jobs; resume_data is plain-text cover letter + highlights

-- Jobs
INSERT INTO job (job_id, title, description, posted_at, status, created_at, updated_at) VALUES
('job-001', 'Staff Software Alchemist — Commerce & Inventory APIs', 'FantaCo sells uncommon deskside wonders (copper lamps, zen fountains, artisan keycaps, the occasional emotionally supportive stapler). We need a senior engineer to evolve our product catalog, orders, and integrations so every SKU feels as magical online as it does in an Imagination Pod. You will design and ship resilient REST APIs, tame PostgreSQL, mentor juniors, and pair with teams who speak both SQL and Dolphin (training provided). Requirements: 5+ years backend development, strong API design, relational databases, and a tolerance for biodegradable glitter in code reviews. Python, Spring, or similar stacks welcome; skepticism toward Philosopher''s Stone feature requests is a plus.', '2026-01-08 09:00:00', 'OPEN', NOW(), NOW());

INSERT INTO job (job_id, title, description, posted_at, status, created_at, updated_at) VALUES
('job-002', 'Principal Frontend Purveyor — Digital Showroom & Checkout Drama', 'Our storefront should feel like a 1920s speakeasy meets a serene Zen garden — password optional, flapper dress code discouraged unless it is Tuesday. Build fast, accessible experiences for discovering bespoke office goods, configuring options, and checking out without existential dread. Requirements: 3+ years modern JavaScript or TypeScript, component architecture, responsive design, WCAG-minded implementation, and willingness to participate in mandatory jazz-hands accessibility audits (metaphorical, mostly). React, Vue, or equivalent; appreciation for monitor light bars and nixie clocks preferred.', '2026-02-12 10:00:00', 'OPEN', NOW(), NOW());

INSERT INTO job (job_id, title, description, posted_at, status, created_at, updated_at) VALUES
('job-003', 'Lead Mythical Infrastructure Wrangler — Platform, CI/CD & Dragon Uptime', 'Keep our clouds fluffier than a griffin feather pillow: Kubernetes or container platforms, CI/CD, observability, infrastructure as code, and incident response with composure during temporal breakroom anomalies (Tuesdays). You will harden pipelines, automate the boring parts, and ensure deployments are safer than office jousting with pool noodles. Requirements: 4+ years platform/DevOps/SRE experience, containers, IaC, and a sense of humor about zero-gravity brainstorming sessions. **This requisition has been filled** by someone who already owns a scepter-shaped USB drive.', '2025-11-20 14:00:00', 'FILLED', NOW(), NOW());

INSERT INTO job (job_id, title, description, posted_at, status, created_at, updated_at) VALUES
('job-004', 'Head of Desk-Accessory Demand Prophecy — Data, Forecasting & Moon-Cheese Metrics', 'Turn signals into strategy: which artisan desk mats move before Mercury retrograde? Will acoustic panels spike after Interpretive Dance Off season? Build forecasts, dashboards, and experiments that connect catalog depth to customer joy. Partner with merchandising and engineering; explain models to executives, owls, and Magic 8-Balls on the Benevolent Overlord Council. Requirements: MS or equivalent depth in statistics/CS/analytics, SQL, Python, pragmatic ML, and storytelling skills. Bonus: experience with recommendation systems for people who buy succulents *and* mechanical keyboards.', '2026-02-28 08:30:00', 'OPEN', NOW(), NOW());

INSERT INTO job (job_id, title, description, posted_at, status, created_at, updated_at) VALUES
('job-005', 'Senior Quality Oracle — Automated Assurance & Ergonomic Ballet', 'FantaCo quality is non-negotiable: if it ships, it must survive real desks, real humans, and the occasional synchronized swivel competition. Own end-to-end and API test automation, flake-hunting, and release gates. Requirements: 3+ years QA automation, modern browser or API test tools, CI integration, and calm under flash-mob drill conditions. **Position closed** — we hired someone whose test plan included a pool-noodle regression suite.', '2025-09-03 11:00:00', 'CLOSED', NOW(), NOW());

-- Applications
INSERT INTO application (application_id, job_id, applicant_name, applicant_email, resume_data, status, submitted_at, created_at, updated_at) VALUES
('app-001', 'job-001', 'Mira Okonkwo', 'mira.okonkwo@example.com', 'Cover letter: I have spent six years building inventory and checkout APIs for specialty retailers. I love the idea of APIs for objects that spark joy — copper diffusers, walnut caddies, the whole Gilded Cage aesthetic. I speak fluent PostgreSQL, Java/Spring and Python, and I once reduced a Friday-afternoon printer jam to a monitoring alert (different industry, same energy). Happy to learn the three required Dolphin phrases after onboarding. Highlights: led migration to event-driven stock updates; mentored four engineers; championed idempotency like it was a competitive sport.', 'UNDER_REVIEW', '2026-01-10 11:30:00', NOW(), NOW());

INSERT INTO application (application_id, job_id, applicant_name, applicant_email, resume_data, status, submitted_at, created_at, updated_at) VALUES
('app-002', 'job-001', 'Jasper Hallowell', 'jasper.hallowell@example.com', 'Hello Happiness Herders — I am a backend engineer (4 yrs) who recently shipped a GraphQL layer for a maker marketplace. I enjoy weird SKUs, strict validation, and documentation that reads like a gentle manifesto. I have not yet parallel-parked a Segway blindfolded, but I did automate a deploy that only breaks when Mercury is in retrograde (we fixed that). Stack: Node and Python, Postgres, Redis, OpenAPI zealot. Seeking a team where "bespoke" is a product feature, not a buzzword.', 'SUBMITTED', '2026-01-14 14:15:00', NOW(), NOW());

INSERT INTO application (application_id, job_id, applicant_name, applicant_email, resume_data, status, submitted_at, created_at, updated_at) VALUES
('app-003', 'job-002', 'Priya Ramanathan', 'priya.ramanathan@example.com', 'Dear FantaCo — Your benefits doc broke my irony detector in the best way. I am a frontend engineer (5 yrs) obsessed with performance, accessibility, and storytelling through layout. I have shipped design systems, reduced LCP on commerce paths, and run A/B tests on checkout flows without summoning temporal anomalies. I would love to build a showroom that sells standing desks and nixie clocks with equal gravitas. Theme song preference: 8-bit chiptune with surprise opera. Portfolio: priya-builds.example.com (placeholder in demo data).', 'INTERVIEW_SCHEDULED', '2026-02-14 09:45:00', NOW(), NOW());

INSERT INTO application (application_id, job_id, applicant_name, applicant_email, resume_data, status, submitted_at, created_at, updated_at) VALUES
('app-004', 'job-002', 'Taylor Vance', 'taylor.vance@example.com', 'Application for Principal Frontend role. I have three years of enterprise dashboard experience focused on data grids and admin tools. I prefer minimal, gray interfaces and have not worked in e-commerce. I am uncomfortable with mandatory whimsy workshops and do not wish to learn Squirrel. Skills: React, TypeScript, REST consumption. Looking for a traditional corporate environment.', 'REJECTED', '2026-02-15 16:20:00', NOW(), NOW());

INSERT INTO application (application_id, job_id, applicant_name, applicant_email, resume_data, status, submitted_at, created_at, updated_at) VALUES
('app-005', 'job-003', 'Elena Vasquez', 'elena.vasquez@example.com', 'To the Infrastructure team — Six years keeping production boring in the good way: Kubernetes, Terraform, GitOps, SLOs, and postmortems that people actually read. I reduced MTTR by tightening observability and taught teams to treat incidents as learning loops, not blame parades. I am drawn to FantaCo because reliable platforms are the unsung hero behind every LED strip and smart mug. Offer stage: excited to help dragons and deploy pipelines coexist peacefully.', 'OFFER_EXTENDED', '2025-11-22 08:00:00', NOW(), NOW());

INSERT INTO application (application_id, job_id, applicant_name, applicant_email, resume_data, status, submitted_at, created_at, updated_at) VALUES
('app-006', 'job-004', 'Sam Okada', 'sam.okada@example.com', 'Hello — I am an analytics/ML engineer (4 yrs) who models demand, seasonality, and promo lift for physical goods. I have built forecasting pipelines in Python + SQL, shipped dashboards stakeholders use, and partnered with ops on inventory targets. Intrigued by FantaCo''s mix of commodity staples and artisan SKUs — that is a fun elasticity problem. I promise not to use the on-site alchemist for personal lead-to-gold conversions. Open to onsite llama tea parties if they improve cross-functional trust.', 'SUBMITTED', '2026-03-01 10:00:00', NOW(), NOW());
