apiVersion: v1
kind: Service
metadata:
  name: fantaco-sales-policy-search-service
  labels:
    app: fantaco-sales-policy-search
spec:
  type: ClusterIP
  selector:
    app: fantaco-sales-policy-search
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
