apiVersion: v1
kind: ConfigMap
metadata:
  name: fantaco-product-config
  labels:
    app: fantaco-product-main
data:
  database.url: "jdbc:postgresql://postgres-prod:5432/fantaco_product"
  database.username: "product"
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    logging.level.com.product=INFO
