apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fantaco-product-service
  labels:
    app: fantaco-product-main
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fantaco-product-service
    weight: 100
