apiVersion: v1
kind: ConfigMap
metadata:
  name: fantaco-sales-order-config
  labels:
    app: fantaco-sales-order-main
data:
  database.url: "jdbc:postgresql://postgres-sord:5432/fantaco_sales_order"
  database.username: "salesorder"
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    logging.level.com.salesorder=INFO
