apiVersion: v1
kind: Service
metadata:
  name: fantaco-sales-order-service
  labels:
    app: fantaco-sales-order-main
spec:
  type: ClusterIP
  selector:
    app: fantaco-sales-order-main
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
