{{- if and .Values.salesorder.enabled .Values.salesorder.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.salesorder.route.name }}
  labels:
    app: {{ .Values.salesorder.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.salesorder.service.name }}
  port:
    targetPort: http
  tls:
    termination: {{ .Values.salesorder.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.salesorder.route.tls.insecureEdgeTerminationPolicy }}
{{- end }}
