apiVersion: v1
kind: Service
metadata:
  name: postgres-hr-recruiting
  labels:
    app: postgres-hr-recruiting
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres-hr-recruiting
      protocol: TCP
      name: postgres-hr-recruiting
  selector:
    app: postgresql-hr-recruiting
