apiVersion: v1
kind: Service
metadata:
  name: postgres-hr-recruiting
  labels:
    app: postgres-hr-recruiting
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: pg-hr-recruit
      protocol: TCP
      name: pg-hr-recruit
  selector:
    app: postgresql-hr-recruiting
