apiVersion: v1
kind: Service
metadata:
  name: mcp-product-service
  labels:
    app: mcp-product
spec:
  type: ClusterIP
  selector:
    app: mcp-product
  ports:
  - port: 9003
    targetPort: 9003
    protocol: TCP
    name: http
